### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by agoose77**
This PR modifies the README to improve the grammar slightly. Hope the PR is acceptable.

### CODE REVIEW

**Comment by rmorshea** [comment]
Yup, no idea what I was thinking with those commas. Thanks!

**Comment by agoose77** [comment]
Thanks!

**Comment by rmorshea** [comment]
Hmm looks like something's up with CI. I'll look into this.

**Comment by rmorshea** [comment]
Merging despite missing CI. Travis doesn't seem to be able to discover this repo anymore for some reason.

**Comment by agoose77** [comment]
Thanks!

**Pull request merged**
