### PR TITLE
closes #38 by removing spectate.core to simplify maintenance

### LINKED ISSUE #38: Refactor To Simplify Core Logic
For a while now I've wanted to basically remove all the logic in `spectate/core.py`. It's certainly clever, but totally unnecessary in hindsight. I think we can get away with a much simpler solution using the new `mvc` interface. In short, the planned refactor will not change the `mvc` API and will simply change its underlying implementation.

In the refactor `Model` classes will be implemented using the `notiifier` context manager:

```python
from spectate import notifier, Model, Undefined

class Dict(Model, dict):

    def __setitem__(self, key, value):
        with notifier(self) as notify:
            old = self.get(key, Undefined)
            super().__setitem__(key, value)
            notify(old=old, new=new, key=key)
```

This is far simpler than the whole `Control` interface used now which is far more complicated.

### PR DESCRIPTION
**Pull request by rmorshea**
I wrote `spectate.core` several years ago, and in retrospect I was simply being far too clever. Removing `spectate.core` will simplify maintenance going into the future.

### CODE REVIEW

**Comment by rmorshea** [comment]
Still need to update documentation.

**Comment by rmorshea** [comment]
@marimeireles feel free to add yourself as a reviewer here since it seems like your the one who used `spectate`.

**Comment by rmorshea** [comment]
Note To Self: Update README + docs to say Python 3 only

**Comment by marimeireles** [comment]
Hey @rmorshea sorry again for not responding earlier, I really missed your ping.
I just tested with ipycytoscape and it seems to work fine.
Thank you a lot for the ping :) & for your work.

**Pull request merged**
